#!/usr/bin/gawk -f
BEGIN{ first=1; OFS="\t"; head="" }
{gsub(//,"")}
/FileName/{cast=gensub(/^.*\\(.*)\.DAT/,"\\1","g",$4)}
# /Bottle/{if (first) {print "File","Cast",$0} else {print "-"}; first=0}
/Bottle/{

	if ($0!=head){
		printf "File        Cast        "
		rem=1;
		while (rem<length($0)){
			nam=substr($0,rem,11);
			rem+=11;
			printf " %s",nam
			}
		printf "\n"
		}
	else {print "-"};
	head=$0
	}
/\(avg\) *$/{
	sub(/\(avg\) *$/,""); 
	sub(/[ADFJMNOS][aceopu][bcglnprtvy] [0-9][0-9] [129][0129][0-9][0-9]/,"\"&\"");
	print FILENAME,cast,$0
	}
