#!/usr/bin/gawk -f
# makes the above-full-scale and below-empty output from makecpt 
# the same as the maximum and minimum output respectively
BEGIN{
	OFS="\t"
	}
/^B/{
	$2=a[1];$3=a[2];$4=a[3]
	}
/^F/{
	$2=b[1];$3=b[2];$4=b[3]
	}
/^[^#]/&&!data{
	data=1; a[1]=$2;a[2]=$3;a[3]=$4
	}
NF>=8{
	b[1]=$6;b[2]=$7;b[3]=$8
	}
{
	print
	}
