# Contents.awk				
# 8lfilter		
# add		
# addcomment		
# adjust_date		
# asc2prs.awk		
# asc2s87		
# autoaxis.awk		
# axis.awk		
# backup		
# caloxysal.awk		
# chcase		
# checkstatus		
# cnv2s87		
# cookiepecker.pl		
# ctdmnmx.awk		
# date2day.m		
# day2date.m		
# ddsparse.awk		
# ddstrans.awk		
# dec2hex		
# distance.awk		
# dos2unix		
# download.s		
# filldisks.s		
# fixdelete		
# fixhrefs		
# fixs87s		Print only major parameter columns from s87s files
# fixstn.awk		
# getpos.awk		
# hex2dec		
# isopyc0.dat		
# isopyc0.grd		
# isopyc1000.dat		
# isopyc1000.grd		
# isopyc500.dat		
# isopyc500.grd		
# isopycnal0.grd		
# isovalue.awk		
# linearcpt		
# magnum.awk		
# makechart		
# mathlib.awk		
# medfilt.awk		
# nowtime		
# okay		
# onedisk.s		
# oxytitr.awk		
# parseadcp.awk		
# pid		
# position_tape		
# proc		
# prs2s87		
# prs2s87.awk		
# ps2gif		
# readme.txt		
# readnews.s		
# readnews.s.bak		
# rot13		
# s872fullt		
# s872fullt.awk		
# s872odv.awk		
# s872table		
# s872table.awk		
# s872table1.awk		
# sealib.awk		Calculate properties of Seawater 
# seatest.awk		
# sfri2s87		
# soffice		
# startterm		Start an xterm
# stnpars1		
# stnpars1.awk		
# stnparse		
# stnparse.awk		
# timelib.awk		
# uniqfile		
# unix2dos		
# update		
# userlist		
# v0802s87.awk		
# vacation.pl		Sends an email message while on vacation
# vertsect		Creates a vertical section of CTD data from s87 files
# whatami		Script to display information about SUN systems
