#!/bin/bash

function printhelp(){
	echo $0: creates a commit message and does \"git commit\"
	exit
}

# Args=$@

while [ $# -gt 0 ] 
do 
   case $1 in 
        -h)    printhelp ;;
	--help) printhelp ;;
   esac
   test $# -gt 0 && shift
done


files=$(git status --porcelain | grep -v "^[ ?]" | awk '{print $2}' )
num=$(git status --porcelain | grep -v "^[ ?]" | wc -l)

if [ ${num} -eq 0 ]; then 
	echo "No files to commit. Run ""git add <filename>"" to stage files." 
	exit 1
fi

if [ ${#files} -le 50 ]; then
	# git commit -m "Updating ${files}"
	MESSAGE="`echo Updating ${files}`"
else
	MESSAGE="Updating ${num} files"
fi

git commit -m "$MESSAGE"

