#!/bin/bash

function printhelp(){
	echo $0: creates a commit message and does \"git commit\"
	exit
}

# Args=$@
# Opt=""

while [ $# -gt 0 ] 
do 
   case $1 in 
        -h)    printhelp ;;
	--help) printhelp ;;
	-a)	Opt="-a" ;;
   esac
   test $# -gt 0 && shift
done

files=$(git commit --dry-run --porcelain $Opt | grep -v "^[ ?]" | awk '{print $2}' )
num=$(git commit --dry-run --porcelain $Opt | grep -v "^[ ?]" | wc -l)

if [ ${num} -eq 0 ]; then 
	echo "No files to commit. Run ""git add <filename>"" to stage files." 
	exit 1
fi

if [ ${#files} -le 50 ]; then
	# git commit -m "Updating ${files}"
	MESSAGE="`echo Updating ${files}`"
else
	MESSAGE="Updating ${num} files"
fi

# git commit -m "$MESSAGE"
git commit $Opt -m "$MESSAGE"

# vi: se nowrap tw=0 :

