#! /bin/bash

if hash gmt 2> /dev/null ; then
	GMTWRAP=gmt
elif hash GMT 2> /dev/null ; then
	GMTWRAP=""
else
	echo "An executable version of GMT is apparently not found in your path." >&2 
	exit 1
fi

if [ "$1" = "--version" ]; then
	Version=$( ( GMT --help || gmt --help ) 2>&1 |
		grep -i version | head -n1 |
		grep -o "[0-9.]*" | head -n1 )
	echo Running version ${Version} of GMT
	exit 
fi

$GMTWRAP $@

