#! /bin/bash
# Wrapper for GMT
# Runs either Version 4 or Version 5 which ever is av ailable. 
# Version 4 has stand-alone commands; Version 5 runs commands as 
# modules via a gmt command. 

# Version 5
if hash gmt 2> /dev/null ; then
	GMTWRAP=gmt
# Version 4
elif hash GMT 2> /dev/null ; then
	GMTWRAP=""
else
	echo "An executable version of GMT is apparently not found in your path." >&2 
	exit 1
fi

if [ "$1" = "--version" ]; then
	Version=$( ( GMT --help || gmt --help ) 2>&1 |
		grep -i version | head -n1 |
		grep -o "[0-9.]*" | head -n1 )
	echo Running version ${Version} of GMT
	exit 
fi

$GMTWRAP $@

