#! /bin/bash

export HISTFILE=/dev/null
export PATH=$PATH:~/IMAGES/pron/bin
export AWKPATH=$AWKPATH:~/IMAGES/pron/bin
# export PROMPT_COMMAND=$(echo $PROMPT_COMMAND | sed "s/;[^;]*bash_eternal_history[^;]*;/; /")

bash --rcfile ~/.bashrc_minimalist

kill -9 $PPID

# vi: se nowrap tw=0 :
