#!/bin/bash
# 
# USAGE: vertsect <options> <s87filenames>
#
# convert the s87 data files to table 
# pass thru project to cut out the data along the transect we need
# blockmean the stations, build a grid file

# 2006-02-15 Tidying up (environment variabiles)
# 2003-09-04 Topography on the chart
# 2003-05-14 Tidying up
# 2002-11-12 At sea Africana 171, taking the bathymetry from the s87 files
# 2001-11-22 At sea Africana 163, add fluorescence plot

TitleStr=${TitleStr:-"Not Named"}
# Skip=${Skip:-$Skip}
Skip=${Skip:-0}
# echo "Skip is $Skip" 1>&2
BadSalt=${BadSalt:-0}
BadOxyg=${BadOxyg:-0}
BadTemp=${BadTemp:-0}
BadFluo=${BadFluo:-1}
CleanUp=${CleanUp:-1}
Topofile=${Topofile}
# Note changing PlotCast requires more changes than I am willing to make
# right now - 2005/06/13. Come back to this at another time.
PlotCast=${PlotCast:-1}

if [ $# = 0 ]
then 
cat << END

USAGE: vertsect <options> <s87filenames>

Plots a vertical section of a line of stations

Plot definition
        -V<l/r/b/t>     Vertical section range [40/250/0/1000]
        -R<w/e/s/n>     map Range [17.5/18.5/-33.5/-32]
	-J<n/r>		reverse the direction of the x-axis

Line definition
	-C<lon/lat>	line Centre
        -A<angle>	line Angle
        -L<length>	line Length
        -E<lon/lat>     line End
        -W<from/to>     line Width
        -G<xgrid/ygrid> Grid size [5/1]

Miscellaneous
	--origcolor	original colour scales
	--nocolor	contours, no shading
	--monocolor	monochrome shading
	--discretecolor	no shading, bands of colour
	--bad[salt|temp|oxyg]	do not plot the bad section
	--nocleanup	do not delete temporary files
	--plotfluor	plot the fluorescence (by default not)
	--nomap		omit the orientation chart
	--nobathy	omit the bathymetry line on the sections

Environment
	TitleStr	SE ["Not Named"]
	Skip		Skip gridding and contouring [0]
	Bad[Salt|Oxyg|Temp]	Don't plot these [0]
	BadFluo		[1]
	CleanUp		Delete temporary files [1]
	BlockSize
	SurfSize
	GridSize
	TempRange,SaltRange,OxyRange	
	TempDelta,SaltDelta,OxyDelta	
	TempScaleTick	
	PlotCast
	Topofile	$Topofile

END
exit 1
fi

Tension=0
VertRange=40/250/0/1000 
MapRange=17.5/18.5/-33.5/-32

GridSize=${GridSize:-"5/1"}
# BlockSize and SurfSize are dependent on GridSize but are set later
TempRange=${TempRange:-"3/23"}
TempDelta=${TempDelta:-"1"}
SaltRange=${SaltRange:-"34.2/35.7"}
SaltDelta=${SaltDelta:-"0.1"}
OxyRange=${OxyRange:-"0/7"}
OxyDelta=${OxyDelta:-"0.5"}
FluoRange=${FluoRange:-"0/2"}
FluoDelta=${FluoDelta:-"0.1"}

FluoScaleTick=${FluoScaleTick:-"f0.1a0.5g${FluoDelta}"}
SaltScaleTick=${SaltScaleTick:-"f0.1a0.5g${SaltDelta}"}
TempScaleTick=${TempScaleTick:-"f1a5g${TempDelta}"}
OxyScaleTick=${OxyScaleTick:-"f1a5g${OxyDelta}"}

XSection=${XSection:-"f10a50"}
YSection=${YSection:="f50a100"}

HoriProj=15.0
VertProj=4.5
Gap=0.8
Offset=2.5

TempScale="-H210  -S0/1 -V1/0.85 -F0/0/1 -B0/0/1"
SaltScale="-H70  -S0/1 -V1/1 -B0/1/1 -F0/0/1"
FluoScale="-H140 -S0/1 -V1/1 -F0/0/1 -B0/0/1"
OxyScale="-H310 -S0/1 -V1/1  -F0/0/1 -B0/0/1"

temppalette=no_green
oxypalette=rainbow
saltpalette=rainbow
fluopalette=red2green

Proj=${HoriProj}c/-${VertProj}c
TitleProj=${Proj}
# StationColor=255/0/0
StationColor=0/1/1
TopTag=WesN
MiddleTag=Wesn
BottomTag=WeSn
NoColor=false
discretecolor=false
NoMap=false
NoBathy=false

Label=8

# Within=-2/2

while [ $# -gt 0 ] 
do 
case $1 in 
        -G*)    GridSize=${1#-?} ;;
	-T*)	Tension=${1#-?} ;;
        -V*)    VertRange=${1#-?} ;;
        -R*)    MapRange=${1#-?} ;;
        -A*)    Angle=-A${1#-?} ;;
        -E*)    End=-E${1#-?} ;;
        -C*)    Center=-C${1#-?} ;;
        -L*)    Length=-L${1#-?} ;;
        -W*)    Within=-W${1#-?} ;;
	-Jr)	Proj=-$Proj 
		Label=2
		;;
	--origcolor)
		TempScale="-H190/380 -B190/1/1 -F380/1/1 -F0/0/1 -B0/0/1"
		SaltScale="-H120/0 -B0/1/1 -F0/0/1"
		OxyScale="-H300/0 -B300/1/1 -F0/1/1  -F0/0/1 -B0/0/1"
		FluoScale="-H300/180 -B300/1/1 -F180/1/1  -F0/0/1 -B0/0/1"
		;;
	--nocolor)
		NoColor=true
		StationColor=0
		TopTag=WEsN
		MiddleTag=WEsn
		BottomTag=WESn
		;;
	--discretecolor)
		discretecolor=true
		TempScale="-T$TempRange/$TempDelta"
		SaltScale="-T$SaltRange/$SaltDelta"
		OxyScale="-T$OxyRange/$OxyDelta"
		FluoScale="-T$FluoRange/$FluoDelta"
		;;
	--monocolor)
		TempScale="-H0 -S0 -V0.2/1 -F0/0/1 -B0/0/0" 
		SaltScale="-H0 -S0 -V0.2/1 -F0/0/1 -B0/0/0" 
		OxyScale="-H0 -S0 -V0.2/1 -F0/0/1 -B0/0/0"
		FluoScale="-H0 -S0 -V1/0.2 -F0/0/1 -B0/0/0"
		StationColor=0
		;;
	--badsal*)
		BadSalt=1
		;;
	--badoxy*)
		BadOxyg=1
		;;
	--badtemp*)
		BadTemp=1
		;;
	--plotfluo*)
		BadFluo=0
		;;
	--nocleanup)
		CleanUp=0
		;;
	--nobathy)
		NoBathy=true
		;;
	--nomap)
		NoMap=true
		;;
        [^-]*)  FileNames=$@ ; shift $# 
		;;
esac
test $# -gt 0 && shift
done

# echo $GridSize 1>&2
BlockSize=${BlockSize:-$GridSize}
SurfSize=${SurfSize:-$BlockSize}

# $datafile has the data projected onto the line
datafile=`uniqfile`

# $castfile has the bathymetry from the deepest point of the cast
castfile=`uniqfile`

# $bathyfile has the bathymetry from the ZZ field in the datafiles
bathyfile=`uniqfile`

# $clipfile has the clip path for the bathymetry
clipfile=`uniqfile`

# $cptfile is the colour map
cptfile=`uniqfile`

# $grdfile has the gridded data
grdfile=`uniqfile`

# $topocon has the contours for the bathymetry
topocon=$(uniqfile)

# echo $datafile 1>&2

# echo -e "\ncastfile="$castfile 1>&2
# echo "clipfile="$clipfile 1>&2
# echo "cptfile="$cptfile 1>&2
# echo "grdfile="$grdfile 1>&2
# echo "datafile="$datafile 1>&2
# echo "bathyfile="$bathyfile 1>&2

LineDef="$Center $End $Length $Angle"

# echo $LineDef
# echo $BadFluo 1>&2

echo $TitleStr 1>&2

gmtdefaults -L |
	awk '
/PAPER_MEDIA/{print $1 " is \"" $3 "\". Use gmtset to change." > "/dev/stderr"}
/COLOR_MODEL/{print $1 " is \"" $3 "\". Use gmtset to change." > "/dev/stderr"}
'

COLOR_MODEL=`gmtdefaults -L | awk '/COLOR_MODEL/{print $3}'`

gmtset						\
	ANOT_FONT		Helvetica	\
	ANOT_FONT_SIZE		12p		\
	BASEMAP_TYPE		plain		\
	BASEMAP_AXES		WESN		\
	COLOR_MODEL		hsv		\
	FRAME_WIDTH		0.075i		\
	HEADER_FONT		Helvetica	\
	HEADER_FONT_SIZE	20p		\
	LABEL_FONT		Helvetica	\
	LABEL_FONT_SIZE		14p		\
	MEASURE_UNIT		inch		\
	PAGE_ORIENTATION	portrait	\
	WANT_EURO_FONT		TRUE		\
	;

for f in $FileNames; do
	gawk -f mathlib.awk -f sealib.awk -f s87depth.awk $f |
	gawk -f mathlib.awk -f s872table1.awk	\
Latitude,Longitude,Depth,Temperature,Salinity,Oxygen,Fluorescence,Station,Bathymetry |
	awk '/-99*/{gsub(/-99*/,"NaN")}{print $1,$2,$3,$4,$5,$6,$7,$8,$9}' 
done |
        project -Fxypqrsz $Within $LineDef -Q -: > $datafile

# Get the bathymetry
# Real bathymetry from etopo5
# project -Frs -Q -G5 $LineDef |
# 	grdtrack -G/usr/local/data/etopo5/etopo5.grd |
# 	gawk '{print $3,-$4}' > $castfile

gawk '  NR==1{lat=$1;lon=$2}
	lat!=$1||lon!=$2{print max;lat=$1;lon=$2}
	{max=$0}
	END{print max}
	' $datafile | 
	gawk '{print $3,$7+5}' | sort -n > $castfile

# (echo castfile ; cat $castfile ) 1>&2

gawk '{print $3,$NF}' $datafile | grep -v NaN | uniq | sort -n > $bathyfile 

# (echo bathyfile; cat $bathyfile ) 1>&2 

# gawk 'BEGIN{m=0;print 0,0}
#	{print $1,$2;if ($1>m){m=$1}}
#	END{print m,0,"\n",0,0}' $castfile > $clipfile

gawk 'BEGIN{m=0;}
	NR==1{print $1,0; a=$1}
	{print $1,$2;if ($1>m){m=$1}}
	END{print m,0,"\n",a,0}' $castfile > $clipfile


# ( echo clipfile ; cat $clipfile ) 1>&2 

###############
# vertical profile Oxygen
DataCol=10
DataRange=$OxyRange
DataScale=$OxyScale
ScaleTick=$OxyScaleTick
ContourDelta=$OxyDelta

if [  $Skip = 0 -a $BadOxyg = 0 ]; then
gawk "{print \$3,\$7,\$$DataCol}" $datafile | \
	blockmean -I$BlockSize -R$VertRange | \
	surface -I$SurfSize -R$VertRange -G$grdfile -T$Tension
fi
if $discretecolor; then
	makecpt -C$oxypalette $DataScale | cleancpt > $cptfile
else
	linearcpt  -N20 -C$DataRange $DataScale > $cptfile
fi
psclip $clipfile -R -JX$Proj -K	-Y${Offset}c
if [  $Skip = 0 -a $BadOxyg = 0 ]; then
	$NoColor || grdimage $grdfile -R -JX -C$cptfile -K -O
	grdcontour $grdfile -R -JX -C$ContourDelta -K -O -A
fi
psclip -C -K -O
gawk '{print $3,$7}' $datafile | psxy -R -JX -Sp -B${XSection}:"Distance (km)":/${YSection}::${BottomTag} -O -K
# psxy $castfile -R -JX -O -K 

if ! $NoBathy ; then
	psxy $bathyfile -R -JX -O -K 
	psxy $bathyfile -R -JX -O -K -Si0.1
fi

pstext -N -R0/10/0/10 -JX -K -O << END
$Label 9.5 12 0 0 1 Oxygen
END

# cat $cptfile 1>&2
$NoColor || psscale -C$cptfile -D`echo $HoriProj | awk '{print $1+0.5 "c"}'`/`echo $VertProj | awk '{print $1/2 "c"}'`/${VertProj}c/0.75c -B$ScaleTick -O -K

echo Done Oxygen 1>&2

###############
# vertical profile Fluor
DataCol=11
DataRange=$FluoRange
DataScale=$FluoScale
ScaleTick=$FluoScaleTick
ContourDelta=$FluoDelta

if [  "$Skip" = "0" -a "$BadFluo" = "0" ]; then
gawk "{print \$3, \$7, \$$DataCol}" $datafile | \
	blockmean -I$BlockSize -R$VertRange | \
	surface -I$SurfSize -R$VertRange -G$grdfile -T$Tension
# fi
if $discretecolor ; then
	makecpt -C$fluopalette $DataScale > $cptfile
else
	linearcpt  -N20 -C$DataRange $DataScale > $cptfile
fi

psclip $clipfile -R -JX$Proj -K -O 				-Y`echo $VertProj $Gap| awk '{print $1+$2 "c"}'`
if [  $Skip = 0 -a $BadTemp = 0 ]; then
	$NoColor || grdimage $grdfile -R -JX -C$cptfile -K -O
	grdcontour $grdfile -R -JX -C$ContourDelta -K -O -A5
fi
psclip -C -K -O
gawk '{print $3,$7}' $datafile | psxy -R -JX -Sp -B${XSection}::/${YSection}::$MiddleTag -O -K
# psxy $castfile -R -JX -O -K 

if ! $NoBathy ; then
	psxy $bathyfile -R -JX -O -K
	psxy $bathyfile -R -JX -O -K -Si0.1
fi

pstext -R0/10/0/10 -JX -K -O << END
$Label 9.5 12 0 0 1 Fluorescence
END

$NoColor || psscale -C$cptfile -D`echo $HoriProj | awk '{print $1+0.5 "c"}'`/`echo $VertProj | awk '{print $1/2 "c"}'`/${VertProj}c/0.75c -B$ScaleTick -O -K

# psscale -C$cptfile -D15.5c/2.75c/5.5c/0.75c -B$ScaleTick -O -K
echo Done Fluorescence 1>&2
fi

###############
# vertical profile Salt
DataCol=9
DataRange=$SaltRange
DataScale=$SaltScale
ScaleTick=$SaltScaleTick
ContourDelta=$SaltDelta

if [ $Skip = 0 -a   $BadSalt = 0 ]; then
gawk "{print \$3,\$7,\$$DataCol}" $datafile | \
	blockmean -I$BlockSize -R$VertRange | \
	surface -I$SurfSize -R$VertRange -G$grdfile -T$Tension
fi
if $discretecolor; then
	makecpt $DataScale -C$saltpalette > $cptfile
else
	linearcpt  -N20 -C$DataRange $DataScale > $cptfile
fi
# echo psclip $clipfile -R -JX$Proj -K -O				-Y`echo $VertProj $Gap | awk '{print $1+$2 "c"}'` 1>&2
psclip $clipfile -R -JX$Proj -K -O				-Y`echo $VertProj $Gap | awk '{print $1+$2 "c"}'`

if [ $Skip = 0 -a $BadSalt = 0 ]; then
	$NoColor || grdimage $grdfile -R -JX -C$cptfile -K -O 
	grdcontour $grdfile -R -JX -C$ContourDelta -K  -O -A
fi
psclip -C -K -O
gawk '{print $3,$7}' $datafile | psxy -R -JX -Sp -B${XSection}::/${YSection}:"Depth (m)":$MiddleTag -O -K
# psxy $castfile -R -JX -O -K 

if ! $NoBathy ; then
	psxy $bathyfile -R -JX -O -K
	psxy $bathyfile -R -JX -O -K -Si0.1
fi

pstext -R0/10/0/10 -JX -K -O << END
$Label 9.5 12 0 0 1 Salinity
END

$NoColor || psscale -C$cptfile -D`echo $HoriProj | awk '{print $1+0.5 "c"}'`/`echo $VertProj | awk '{print $1/2 "c"}'`/${VertProj}c/0.75c -B$ScaleTick -O -K

# psscale -C$cptfile -D15.5c/2.75c/5.5c/0.75c -B$ScaleTick -O -K

echo Done Salinity 1>&2

###############
# vertical profile Temp
DataCol=8
DataRange=$TempRange
DataScale=$TempScale
ScaleTick=$TempScaleTick
ContourDelta=$TempDelta

if [  $Skip = 0 -a $BadTemp = 0 ]; then
gawk "{print \$3, \$7, \$$DataCol}" $datafile | \
	blockmean -I$BlockSize -R$VertRange | \
	surface -I$SurfSize -R$VertRange -G$grdfile -T$Tension
fi
if $discretecolor; then
	makecpt -C$temppalette $DataScale  > $cptfile
else
	linearcpt  -N20 -C$DataRange $DataScale > $cptfile
fi
psclip $clipfile -R -JX$Proj -K -O 				-Y`echo $VertProj $Gap | awk '{print $1+$2 "c"}'`
if [  $Skip = 0 -a $BadTemp = 0 ]; then
	$NoColor || grdimage $grdfile -R -JX -C$cptfile -K -O
	grdcontour $grdfile -R -JX -C$ContourDelta -K -O -A5
fi
psclip -C -K -O
gawk '{print $3,$7}' $datafile | psxy -R -JX -Sp -B${XSection}::/${YSection}::${TopTag} -O -K
# psxy $castfile -R -JX -O -K 

if ! $NoBathy ; then
	psxy $bathyfile -R -JX -O -K
	psxy $bathyfile -R -JX -O -K -Si0.1
fi

pstext -R0/10/0/10 -JX -K -O << END
$Label 9.5 12 0 0 1 Temperature
END


$NoColor || psscale -C$cptfile -D`echo $HoriProj | awk '{print $1+0.5 "c"}'`/`echo $VertProj | awk '{print $1/2 "c"}'`/${VertProj}c/0.75c -B$ScaleTick -O -K

# psscale -C$cptfile -D15.5c/2.75c/5.5c/0.75c -B$ScaleTick -O -K

echo Done Temperature 1>&2



  MapFrame=`echo $MapRange | gawk -f axis.awk`
  # Along side
  # pscoast -Di -JM5.3c -R$MapRange -G150 -B$MapFrame:."$TitleStr":wESn -O -K			-X18c -Y-12c
  # Above

###############
# station distribution

if $($NoMap) ; then

  echo 50 80 24 0 0 TC "$TitleStr" |
	pstext -N -JX$TitleProj -R0/100/0/100 -O -K -Y`
		echo $VertProj $Gap | awk '{print $1+1+$2 "c"}'
		`

  FRAMECOL=$(gmtdefaults -L | grep BASEMAP_FRAME_RGB | awk '{print $1,$3}')
  FRAMEPEN=$(gmtdefaults -L | grep FRAME_PEN | awk '{print $1,$3}')

  gmtset BASEMAP_FRAME_RGB 0/0/1	FRAME_PEN 0p 
  psbasemap -R -JX -B:.:  -O

  gmtset $FRAMECOL
  gmtset $FRAMEPEN
  
else
  echo 5 80 24 0 0 0 "$TitleStr" |
	pstext -N -JX$TitleProj -R0/100/0/100 -O -K -Y`
		echo $VertProj $Gap | awk '{print $1+1+$2 "c"}'
		`

  pscoast -Di -JM5.3c -R$MapRange -G150 -O -K -X9.8c

  if [ -e "$Topofile" ]; then 
	  echo "1000 c" > $topocon
	  grdcontour $Topofile -JM -R -C$topocon  -K -O 
  fi

  # project -Frs $LineDef -Q -G5 | grdtrack -G/usr/local/data/etopo5/etopo5.grd | psxy -R -JM -W10 -O -K
 
  head -1q $FileNames | awk '{print $5,$4}' | psxy -R$MapRange -JM -Sc0.03 -G0 -O -K

  # /home/duncombe/DATA/COAST/formatcoastpts.awk ~/DATA/COAST/coastpts.txt | gawk '{printf "%g %g 8 0 1 LM %s\n",$2,$1,$3 " " $4 }' | pstext -R -JM -O -K

  # gawk '{print $1,$2}' $datafile | sort | uniq | psxy -R -JM -Sc0.05 -B$MapFrame:."$TitleStr":wESn -G255/0/0 -O 
  gawk '{print $1,$2}' $datafile | sort | uniq | psxy -R -JM -Sc0.05 -G$StationColor -O -K
  psbasemap -R -JM -B${MapFrame}wESn -O
  # psxy -R -JM -Sc0.1 -G0/255/0 -O

fi

##############
# clean up the mess

if [ $CleanUp = 1 ]; then
	rm $castfile $clipfile $cptfile $grdfile $datafile $bathyfile $topocon
fi

# Reset the gmtdefaults to rational values
gmtset COLOR_MODEL $COLOR_MODEL

# cat << TESTING > /dev/null

echo "$0 complete" 1>&2

